### ISSUE TITLE
docker-entrypoint.sh doesn't seem to be executed

### ISSUE THREAD

**Issue by alfonsrv** [funnydman/confetti#5]
I initially noticed `collectstatic` and `migrate` didn't run automatically when rolling out a new instance.

Adding a test statement doesn't seem to result in the expected behavior.

```bash
#!/usr/bin/env sh
set -x
echo "Test" > /app/test
...
```

**Comment by funnydman** [comment]
@alfonsrv Hello. How to reproduce this issue? Can you provide more information?

**Comment by funnydman** [comment]
@alfonsrv Because nobody replied, I will close this issue for now.
